name: Build Package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9' 

    - name: Create package
      run: |
        cp requirements.txt requirements.txt.orig 
        sed '/boto3/d' requirements.txt.orig > requirements.txt
        pip install --target ./package -r requirements.txt
        cp my-deployment-package.zip package

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: my-deployment-package
        path: package
